### ISSUE TITLE
Task list

### ISSUE THREAD

**Issue by mayraamaral** [mayraamaral/portfolio#8]
- [ ] Domínio https://mayra.dev
- [ ] Menu
- [ ] *Mobile* Menu
- [ ] Seção banner
- [ ] *Mobile* Seção banner
- [ ] Seção sobre mim
- [ ] *Mobile* Seção sobre mim 
- [ ] Seção experiência
- [ ] *Mobile* Seção experiência
- [ ] Seção projetos
- [ ] *Mobile* Seção projetos
- [ ] Seção contato
- [ ] *Mobile* Seção contato
---------------------------------------
- [ ] Versão em inglês
- [ ] Currículo em inglês
---------------------------------------
- [ ] Versão tablet
